# Generated by Django 2.1 on 2019-08-28 08:01

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('video', models.CharField(max_length=500, verbose_name='视频地址')),
                ('content', models.TextField(verbose_name='内容')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('alterdate', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('browse_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('praise', models.IntegerField(default=0, verbose_name='点赞')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='NavModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=20, verbose_name='类别')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('Nav_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_nav', to='blog.NavModel', verbose_name='根')),
            ],
        ),
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片名称')),
                ('picture', models.ImageField(upload_to=blog.models.user_avatar_path, verbose_name='图片')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
            ],
        ),
        migrations.AddField(
            model_name='navmodel',
            name='nav_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PictureModel', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='图片', to='blog.PictureModel', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='nav1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nav1', to='blog.NavModel', verbose_name='一级类别'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='nav2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nav2', to='blog.NavModel', verbose_name='二级类别'),
        ),
    ]
