# Generated by Django 2.1 on 2019-08-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmodel',
            name='nav_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PictureModel', verbose_name='图片'),
        ),
    ]
