# Generated by Django 2.1 on 2019-08-17 02:37

import blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('author', models.CharField(max_length=10, verbose_name='作者')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('picture', models.ImageField(default='blog/img/icon/icon.png', upload_to=blog.models.user_avatar_path, verbose_name='头像')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('alterdate', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('browse_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('praise', models.IntegerField(default=0, verbose_name='点赞')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='NavModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=6, verbose_name='类别')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('Nav_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_nav', to='blog.NavModel', verbose_name='根')),
            ],
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='nav1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nav1', to='blog.NavModel', verbose_name='一级类别'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='nav2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nav2', to='blog.NavModel', verbose_name='二级类别'),
        ),
    ]
