# Generated by Django 2.1 on 2019-08-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190817_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='video',
            field=models.CharField(max_length=500, verbose_name='视频地址'),
        ),
    ]
