# Generated by Django 2.1 on 2019-08-23 04:00

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190821_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='图片名称')),
                ('picture', models.ImageField(upload_to=blog.models.user_avatar_path, verbose_name='图片')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
            ],
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='图片', to='blog.PictureModel', verbose_name='图片'),
        ),
    ]
