# Generated by Django 2.1 on 2019-08-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190823_0400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='picture',
            new_name='article_picture',
        ),
    ]
