# Generated by Django 2.1 on 2019-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190824_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmodel',
            name='nav_name',
            field=models.CharField(max_length=20, verbose_name='类别'),
        ),
    ]
